# =============================================================================
# Docker Stack Configuration - Facundo Growth
# =============================================================================
#
# Descripción: Stack de Docker Swarm para Frontend (Astro + Blog API integrado)
# Versión: 2.0.0
# Última actualización: 2025-11-20
#
# Servicios incluidos:
# - frontend: Astro SSR (puerto interno: 4321) → facundogrowth.com
#   Incluye Blog API integrado en /api/admin/posts
#
# Requisitos:
# - Docker Swarm inicializado
# - Traefik 2.x desplegado y corriendo
# - Red "network_public" creada
# - Variables de entorno configuradas en .env.production
#
# =============================================================================

version: '3.8'

services:
  # ===========================================================================
  # Frontend Service - Astro SSR + Blog API
  # ===========================================================================
  frontend:
    image: facundozupel/frontend:latest

    # Configuración de deployment
    deploy:
      mode: replicated
      replicas: 2  # Alta disponibilidad con 2 réplicas

      # Placement constraints
      placement:
        preferences:
          - spread: node.id  # Distribuir en diferentes nodos

      # Rolling update strategy
      update_config:
        parallelism: 1  # Actualizar 1 replica a la vez
        delay: 10s
        failure_action: rollback
        monitor: 30s
        order: start-first  # Iniciar nueva replica antes de detener la vieja

      # Rollback configuration
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 10s
        order: stop-first

      # Resource limits
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

      # Restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      # Traefik Labels (configuración específica para Traefik v2.x)
      labels:
        # Enable Traefik for this service
        - "traefik.enable=true"

        # Service configuration
        - "traefik.http.services.frontend-service.loadbalancer.server.port=4321"
        - "traefik.http.services.frontend-service.loadbalancer.healthcheck.path=/"
        - "traefik.http.services.frontend-service.loadbalancer.healthcheck.interval=30s"
        - "traefik.http.services.frontend-service.loadbalancer.healthcheck.timeout=5s"

        # Router for HTTP (redirect to HTTPS)
        - "traefik.http.routers.frontend-http.rule=Host(`facundogrowth.com`)"
        - "traefik.http.routers.frontend-http.entrypoints=web"
        - "traefik.http.routers.frontend-http.middlewares=redirect-to-https@docker"

        # Router for HTTPS
        - "traefik.http.routers.frontend-https.rule=Host(`facundogrowth.com`)"
        - "traefik.http.routers.frontend-https.entrypoints=websecure"
        - "traefik.http.routers.frontend-https.tls=true"
        - "traefik.http.routers.frontend-https.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.frontend-https.service=frontend-service"
        - "traefik.http.routers.frontend-https.middlewares=frontend-security-headers@docker"

        # Middleware: Redirect HTTP to HTTPS
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

        # Middleware: Security headers
        - "traefik.http.middlewares.frontend-security-headers.headers.frameDeny=true"
        - "traefik.http.middlewares.frontend-security-headers.headers.browserXssFilter=true"
        - "traefik.http.middlewares.frontend-security-headers.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.frontend-security-headers.headers.stsSeconds=31536000"
        - "traefik.http.middlewares.frontend-security-headers.headers.stsIncludeSubdomains=true"
        - "traefik.http.middlewares.frontend-security-headers.headers.stsPreload=true"
        - "traefik.http.middlewares.frontend-security-headers.headers.customResponseHeaders.X-Powered-By="
        - "traefik.http.middlewares.frontend-security-headers.headers.customResponseHeaders.Server="

        # Swarm-specific labels
        - "traefik.docker.network=network_public"

    # Environment variables
    environment:
      # Astro configuration
      - HOST=0.0.0.0
      - PORT=4321
      - NODE_ENV=production

      # Blog API Auth
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

    # Health check (Docker level)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4321/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

    # Networks
    networks:
      - network_public

# =============================================================================
# Networks Configuration
# =============================================================================

networks:
  network_public:
    external: true
    name: network_public

# =============================================================================
# Notas de Configuración
# =============================================================================
#
# 1. DOMINIO:
#    - Frontend + Blog API: facundogrowth.com
#    - Blog API endpoints: facundogrowth.com/api/admin/posts
#
# 2. REPLICAS:
#    - Frontend: 2 réplicas (1GB RAM, 1 CPU cada una)
#    - Ajustar según carga esperada y recursos disponibles
#
# 3. RECURSOS TOTALES:
#    - RAM: 2GB total (1GB por réplica)
#    - CPU: 2 total (1 CPU por réplica)
#
# 4. HEALTH CHECKS:
#    - Endpoint: / (intervalo 30s, timeout 5s, start 60s)
#
# 5. SEGURIDAD:
#    - Headers de seguridad habilitados
#    - HTTPS forzado con Let's Encrypt
#    - Usuario no-root en el container
#    - Blog API protegido con HTTP Basic Auth
#
# 6. VARIABLES DE ENTORNO NECESARIAS:
#    - ADMIN_PASSWORD: Password para endpoints /api/admin/*
#
# 7. DEPLOYMENT:
#    Exportar variables de .env.production:
#      export $(cat .env.production | xargs)
#    Deploy del stack:
#      docker stack deploy -c docker-stack-full.yml facundogrowth
#
# 8. MONITOREO:
#    Ver servicios:
#      docker service ls
#    Ver logs:
#      docker service logs -f facundogrowth_frontend
#
# 9. ACTUALIZACIÓN:
#    Frontend:
#      docker service update --image facundozupel/frontend:2.0.0 facundogrowth_frontend
#
# 10. ESCALADO:
#     Escalar frontend:
#       docker service scale facundogrowth_frontend=3
#
# 11. BLOG API:
#     - Integrado en Astro SSR
#     - Endpoints en /api/admin/posts
#     - Posts persisten como archivos .md en src/content/blog/
#     - Ver API_BLOG_GUIDE.md para documentación completa
#
# =============================================================================
